import Head from 'next/head'
import {getStoryblokApi, StoryblokComponent, useStoryblokState} from "@storyblok/react";

export const getStaticProps = async ({params, preview}) => {

    const slug = params.slug.toString();

    const sbParams = {
        version: preview ? 'draft' : 'published',
    }

    const storyblokApi = getStoryblokApi();
    const {data} = await storyblokApi.getStory(slug, sbParams);

    return {
        notFound: !preview && !data.story,
        props: {
            initialStory: data.story,
            preview: preview || false,
        },
        revalidate: 3600
    }
}

export const getStaticPaths = async () => {
    const storyblokApi = getStoryblokApi();
    const links = await storyblokApi.getAll('cdn/links', {preview: true})
    const paths = links.map(({slug}) => ({params: {slug}}));

    return {
        paths,
        fallback: false,
    }
}

const Home = ({initialStory, preview}) => {
    const story = useStoryblokState(initialStory, undefined, preview);

    return (
        <>
            <Head>
                <title>{story.name}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <StoryblokComponent
                blok={story.content}/>
        </>
    )
}

export default Home;
