import Head from 'next/head'
import {getStoryblokApi, StoryblokComponent, useStoryblokState} from "@storyblok/react";

export const getStaticProps = async () => {
    const slug = 'home'
    const storyblokApi = getStoryblokApi();
    const {data} = await storyblokApi.getStory(slug);
    return {
        props: {
            initialStory: data ? data.story : false,
        },
        revalidate: 3600
    }
}

const Home = ({initialStory}) => {
    const story = useStoryblokState(initialStory);

    return (
        <>
            <Head>
                <title>{story.name}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <StoryblokComponent
                blok={story.content} />
        </>
    )
}

export default Home;
